### ISSUE TITLE
Users Page

### ISSUE THREAD

**Issue by williamluke4** [grassrootseconomics/sarafu.network#10]
Addresses Clickable -> get user from account -> /admin/user/[id]

**Comment by WillRuddick** [comment]
add in the ability to have / change aliases: https://github.com/grassrootseconomics/sarafu.network/issues/18

**Comment by WillRuddick** [comment]
add in contact information??

**Comment by WillRuddick** [comment]
Addresses Clickable -> get user from account -> /admin/user/[id]
similar to public user page: https://github.com/grassrootseconomics/sarafu.network/issues/68
