### ISSUE TITLE
Add Pool Creation

### ISSUE THREAD

**Issue by williamluke4** [grassrootseconomics/sarafu.network#129]
![12](https://github.com/grassrootseconomics/sarafu.network/assets/10773719/da5dd628-df2f-4dec-86db-7dc55c2a37b9)
![13](https://github.com/grassrootseconomics/sarafu.network/assets/10773719/2050cf8c-1ca0-4641-acda-283818481f96)
![14](https://github.com/grassrootseconomics/sarafu.network/assets/10773719/4cea99bf-bc22-4ea2-abc7-7c232a83bce1)

**Comment by WillRuddick** [comment]
Awesome. The first iteration is good. 

A few things missing MVP:

Ill put another issue
