### ISSUE TITLE
publish token fails

### ISSUE THREAD

**Issue by nolash** [grassrootseconomics/sarafu.network#131]
tried add LASH token with wallet 0x9E24675E81126f6fbC8eBf8DB7Cb22869D160696

error message popup telling (paraphrase) "failed add to graph"

**Comment by WillRuddick** [comment]
couldn't reproduce.
Was this through a browser? What wallet?

**Comment by nolash** [comment]
yes browser, cant remember wallet but probably metamask, possibly brave wallet.

**Comment by williamluke4** [comment]
This should be fixed.

**Comment by nolash** [comment]
still fails

**Comment by williamluke4** [comment]
This failed for a different error and is fixed
