### ISSUE TITLE
Page titles on Pools undefined

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#151]
![image](https://github.com/user-attachments/assets/16cfa115-b8eb-452a-bfff-68e41811a3dc)
showing up as undefined.

This is when pasting the links on social media

**Comment by Isavary** [comment]
> ![image](https://private-user-images.githubusercontent.com/12640165/355783866-16cfa115-b8eb-452a-bfff-68e41811a3dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjcwNjcsIm5iZiI6MTcyMzYyNjc2NywicGF0aCI6Ii8xMjY0MDE2NS8zNTU3ODM4NjYtMTZjZmExMTUtYjhlYi00NTJhLWJmZmYtNjhlNDE4MTFhM2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNjc5Yjc1NzRjMmY0ODRkZWY0ZjI2N2NjZWY3NTJkMzBkYjE0MDcwNTNiNTllNDgwZTdkYzRkMDk1OTAwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kq14mPJ8oTK4CIAKzCEKwoh_1cGXqsRV2sykVlgveA) showing up as undefined.
> 
> This is when pasting the links on social media

Exactly!

And now it's displaying the link as sarafu.network. Can this be Kilifi Culture instead?
![Display Name](https://github.com/user-attachments/assets/c92b4a9c-7729-4240-9c93-f7a3ffbbc33a)

How soon can we make it happen so I can start sharing the link?

**Comment by Isavary** [comment]
How do I delete Baba Vouchers?
I have tried selecting the trash icon then clicking update, and also trashing it and the going back to the previous page without clicking update
![Deleting Voucher](https://github.com/user-attachments/assets/d1199d4a-ac30-4382-a86a-12768c03cbd2)

**Comment by williamluke4** [comment]
Fixed
