### ISSUE TITLE
Formats for sending to phone number

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#153]
Please allow:
+254 729 351 383
+254729351383
254 729 351 383
254729351383
0729351383

(remove and spaces and ) and accept a 0 or 254)

**Comment by williamluke4** [comment]
fixed by https://github.com/grassrootseconomics/sarafu.network/commit/1b9dc99da6c8c3419373d135eb5afb2be2966ffc
