### ISSUE TITLE
Deleting Vouchers in Pool

### ISSUE THREAD

**Issue by Isavary** [grassrootseconomics/sarafu.network#157]
How do I delete Baba Vouchers?

I've selected the trash icon and then clicked on update, put my password 3x and then nothing happens. I went back to the edit icon besides the Baba  Vouchers, hit delete and then closed the window and refreshed the page, nothing happens!

![Delete Baba](https://github.com/user-attachments/assets/092e801d-09e5-41d3-ba19-c94ac9b37d60)

**Comment by williamluke4** [comment]
Hi @Isavary, can you please try just clicking delete and wait? You do not need to click update after delete

**Comment by williamluke4** [comment]
Thank you @Isavary, This should now be fixed
