### ISSUE TITLE
Add token to pool by address and index

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#165]
People want to add all kinds of Celo tokens to pools -

Let them add by contract address.
and also start indexing that token .... (index all tokens that are in pools)

**Comment by williamluke4** [comment]
This has been done on my side. @kamikazechaser Is there something you need to do for the indexing or is that already taken care of?

**Comment by kamikazechaser** [comment]
Any token added to any of our pools will be auto indexed.

The pool itself must exist in our pool registry.
