### ISSUE TITLE
low character limit on map select

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#182]
64 character limit when choosing a map location - doesn't work for many locations / addresses for user and vouchers. 

expand to 128 at least

**Comment by WillRuddick** [comment]
@kamikazechaser this one is bugging folks

**Comment by kamikazechaser** [comment]
Constraints were already dropped here: https://github.com/grassrootseconomics/cic-graph/commit/ec1b912081e4a9a05d5653b9b58ad549e8242a1b
