### ISSUE TITLE
Clicking More information on Voucher Creation

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#187]
![image](https://github.com/user-attachments/assets/f0c604d0-3bca-4a09-9467-871d44e1df99)
Clicking more information here - it will show the info for a second then take you back to the beginning of the steps

**Comment by williamluke4** [comment]
fix by https://github.com/grassrootseconomics/sarafu.network/commit/009ec59e33a5dd7856491d98810ed78ba4d7fe26
