### ISSUE TITLE
Not seeing transactions on cKES

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#189]
https://sarafu.network/vouchers/0x456a3D042C0DbD3db53D5489e98dFb038553B0d0
no transactions showing here also on the visualization

**Comment by kamikazechaser** [comment]
Added in https://github.com/grassrootseconomics/eth-tracker/blame/master/internal/handler/token_transfer.go#L17. Needs upgrade on running instance.

**Comment by WillRuddick** [comment]
still open @kamikazechaser  ?

**Comment by kamikazechaser** [comment]
@WillRuddick depends on https://github.com/grassrootseconomics/eth-tracker/issues/61
