### ISSUE TITLE
Index Pool incoming Transfers (like a deposit)

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#191]
I just transferred 10 cUSD with a normal transaction to https://sarafu.network/pools/0x48a953cA5cf5298bc6f6Af3C608351f537AAcb9e
and it worked I now see the amount in there .... 

But.... there is no event in the transactions .... could this be something we watch for?

It is important because someone my accidentally send a large amount to the pool and we need know. It could also be a **token not even allowed in the pool** and the pool owner could then choose to add it to the pool registry to access it.

**Comment by kamikazechaser** [comment]
This works on the latest tracker (tested on Alfajores). We need to backport the latest tracker to work with the current (old) Celo. Untill then, it will be invisible. Note that the tracker will pick up all old events when it is re-run.
