### ISSUE TITLE
Gas Gifting - Request Form

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#22]
We need a way to add people to our gas gifting registry. 

MVP
- [ ] Ability to edit (Grassroots Economists) list for who can add people to the registry.
- [ ] Form to subscribe (can subscribe for another also)
     if you are on the Grassroots Economists list then the subscriber will enter the registry automatically 
     
For future: the subscriber can enter information about themselves and their vouchers.

**Comment by kamikazechaser** [comment]
@WillRuddick It would be a page with two buttons:

1. "Claim gas"- Calls the `gimme() fn on the Faucet contract`
2. "Claim gas for (address of the user)"- Calls the `giveTo() fn on the Faucet contract`. 3rd party triggers release on behlaf of someone else.

On our end we need to:

- Automatically or manually add users to the registry given some criteria
- Control Faucet parameters (amount and cooldown period)

We can have multiple facuets + registries, each with different parameters and possibly additional users with write permission.

**Comment by WillRuddick** [comment]
> @WillRuddick It would be a page with two buttons:
> 
>     1. "Claim gas"- Calls the `gimme() fn on the Faucet contract`
> 
>     2. "Claim gas for (address of the user)"- Calls the `giveTo() fn on the Faucet contract`. 3rd party triggers release on behlaf of someone else.
> 
> 
> On our end we need to:
> 
>     * Automatically or manually add users to the registry given some criteria
> 
>     * Control Faucet parameters (amount and cooldown period)
> 
> 
> We can have multiple facuets + registries, each with different parameters and possibly additional users with write permission.

ok, so instead of auto-topping them up - we have them make a request?
i.e. _(out of Celo - click here to sign up for our faucet)_

**Comment by kamikazechaser** [comment]
Yes. Auto topping up is also an option. Either approach is fine. Since we know the cooldowns and thresholds we can do it for them.

**Comment by WillRuddick** [comment]
We need a way to add people to our gas gifting registry.

MVP

- [ ] Ability to edit (Grassroots Economists) list for who can add people to the registry.
- [ ] Form to subscribe (can subscribe for another also)
- [ ] if you are on the Grassroots Economists list then the subscriber will enter the registry automatically
- [ ] 

For future: the subscriber can enter information about themselves and their vouchers.

**Comment by WillRuddick** [comment]
can people make 1 voucher a week?

1 voucher per product? = cool!

**Comment by WillRuddick** [comment]
regarding the gas gifitng subscription (promise)

**Comment by williamluke4** [comment]
USSD Max Amount: 0.035

- User Creates Wallet
- Modal Popup (Request Gas)
	- Input User Info (Optional)
	- Request -> DB(Accounts:GasStatus (Registered | Requested | Rejected)
- Staff Member
	- Approve Request DB(Accounts:GasApprover: Address/ID of Approver)
	- Redis (Nonce)

![image](https://github.com/grassrootseconomics/sarafu.network/assets/10773719/625552dc-273c-4f4c-914b-b14fd75ee4ad)

**Needs:**
- Separate User Index
- Separate Faucet
- Separate SimplePeriod

**Comment by kamikazechaser** [comment]
Deploy:

- [ ] Gas Faucet
- [ ] Period Backend
- [ ] User Index

Params:

- [ ] Threshold amount?
- [ ] Cooldown Period?

**Comment by kamikazechaser** [comment]
faucet=0xecfea80af74ed69e50cce304819b4491b4ccfdb3
period=0x70904bF37869a3078e201d20F3408E3Ef9E3cF89
user_index=0x8b73a2c9e88d780cc2a1cbec0e8b3a366eb11a69
contract_registry=0x14367dfEF3a71764Aa83393c58104C04b2e71955

**Comment by kamikazechaser** [comment]
amount=0.015 CELO
threshold=0.00375 CELO
period=24hrs

**Comment by WillRuddick** [comment]
Please check out https://github.com/grassrootseconomics/sarafu.network/issues/42
note that Gas Gifting is related to our Validation Node's purpose

**Comment by WillRuddick** [comment]
integrate into: Profile page: https://github.com/grassrootseconomics/sarafu.network/issues/10

**Comment by kamikazechaser** [comment]
```
amount=0.015 CELO
threshold=0.00375 CELO
period=24hrs
```

**Comment by WillRuddick** [comment]
possibly some way to auto-add people for batch printing accounts (paper wallets?) @kamikazechaser
