### ISSUE TITLE
Allow for unknown quant. and freq. & desc.

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#24]
![image](https://github.com/grassrootseconomics/sarafu.network/assets/12640165/69d84af3-d2f3-48eb-b25f-a3474bf7bbc7)
Please allow for a user not knowing exactly quantity and frequency and description

**Comment by WillRuddick** [comment]
please make the default quantity [1] and frequency daily

**Comment by WillRuddick** [comment]
/// Offering 1st UX – voucher comes from the offering …. express the asset(s)

**Comment by williamluke4** [comment]
> please make the default quantity [1] and frequency daily
Done
