### ISSUE TITLE
Gas Subscription – Referals

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#42]
Recommendations: 

**Rules:**
If **3 people** on the existing gas registry recommend an address it is added to the registry for gas gifting. 
Note that with staff they can add to the registry with no limits, But for recommendations - you can only have **5 outstanding** referrals and can only add **5 per day max** 

**UX**
![image](https://github.com/grassrootseconomics/sarafu.network/assets/12640165/55d05a48-15d4-47bb-9a9f-a4a61d02ec28)

We would need a Referral page for the user - (part of my profile) my_Referrals that shows 5 slots and their status as well as past Referral and their number of transactions. This would be useful for staff as well.

list: with 5 slots
Referral Address, Status (pending 1/3, completed 3/3 ), Options (Remove, Edit)
1.
2.
...
5.

Historic Referral:
Referral Address, num_transactions 
1.
2. 

**notes**

**Dangers**
Avoid the situation where someone can sibyl attack for gas through time based limiting.  
Someone with 3 accounts could auto-add 5 more addresses daily. Now with 8 addresses they can add 5+5 =10 daily (2 sets of 3 recommendations), and with the next day they can have 5x(10+3)/3 more users and so on. 
Tracking and removal of sibyl attack ?

Any three to recommend seems like something we could keep on the sarafu.network end rather than an open blockchain contract - as we test etc. 

Gas gifting was one of the core purposes of our Celo validation node. 
related issue: https://github.com/grassrootseconomics/sarafu.network/issues/22

**Comment by sirpy** [comment]
From our faucet experience, savy users will take the daily max subsidy they can get. They will sybil attack if possible.
I don't see a way around it without a strong anti-sybil mechanism.
We have our uniquness verification, what you suggest here is more like brightid's social graph.
So for sybil resistance you can use our infrastructure or you can try to integrate with brightid and whitelist people in the registry if their sybil score in brightid is good enough. So instead of adding users to the registry the users form connections on brightid graph and then a user request your backend to add himself to the registery if his score is good enough

**Comment by WillRuddick** [comment]
@sirpy our default right now is that we train and accredit people (GEs) who are free to add people to the gas registry. 
We can remove from the registry and also remove GEs. (this has been straight forward while doing some fraud detection)
vs any 3 recommendations, we would only slow down a sybil-attack and fraud detection/ Spotting sybil-attacks where Celo is being harvested is not terribly hard and those address can be removed - but using BrightID sounds interesting - we're trying to avoid any form of hard KYC.

**Comment by sirpy** [comment]
We are not doing hard kyc, just anonymized face verificaiton.
Yeah harvesting could be detected
That's our faucet contract https://github.com/GoodDollar/GoodProtocol/blob/master/contracts/fuseFaucet/Faucet.sol
A simple harvesting check we do
https://github.com/GoodDollar/GoodServer/blob/af28e7f81a61e94e773b106b301cdd3592e0cb75/src/server/blockchain/explorer.js#L33

**Comment by WillRuddick** [comment]
> We are not doing hard kyc, just anonymized face verificaiton. Yeah harvesting could be detected That's our faucet contract https://github.com/GoodDollar/GoodProtocol/blob/master/contracts/fuseFaucet/Faucet.sol A simple harvesting check we do https://github.com/GoodDollar/GoodServer/blob/af28e7f81a61e94e773b106b301cdd3592e0cb75/src/server/blockchain/explorer.js#L33

Thanks looks interesting. (ping @kamikazechaser )
