### ISSUE TITLE
Unique tokens held list

### ISSUE THREAD

**Issue by kamikazechaser** [grassrootseconomics/sarafu.network#47]
Right now the "send to" list comntains all CAV's. We could filter that out to only include the list of CAV's held by the user.

Should this be part of a new API?

**Comment by WillRuddick** [comment]
This is done by @williamluke4  (while there is a select all button - which I think is not needed.)
What would be nice would be the ability to paste in a contract address 

any risk of token spoofing ... I like to see the contract address sometimes before sending to make sure I have the right token/voucher
