### ISSUE TITLE
Make Voucher icon and Symbol clickable on history

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#59]
![image](https://github.com/grassrootseconomics/sarafu.network/assets/12640165/d2d1ec8a-5739-4de4-8835-1bffe10e8ae9)

Enable user to click on the voucher symbol or logo to goto the voucher page (just like on balances)

**Comment by williamluke4** [comment]
fixed : https://github.com/grassrootseconomics/sarafu.network/commit/c5211b6c4693b374dc8602a33b291057f459781c
