### ISSUE TITLE
Community Fund Changable

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/sarafu.network#62]
![image](https://github.com/grassrootseconomics/sarafu.network/assets/12640165/0f37eced-2098-419d-a2a9-f472635913b9)
This address is wrong here: @williamluke4 
(but the balance is correct)?

The community fund should be pointing at: 
https://explorer.celo.org/mainnet/address/0x42E57db57d86a29d11F3ff29290F47D04A9A41dC/tokens#address-tabs
This has the right balance. ~1.3k KPS

Note that when doing a balance check on KPS it say the Community Fund has Zero in it.  @PhilipWafula  (Mbui has more details)

**Comment by kamikazechaser** [comment]
Updated at https://sarafu.network/vouchers/0x2c51672692F0E6b93c1cEc19543785DAafC714E1

**Comment by WillRuddick** [comment]
note that the owner being able to change the community fund should be available on sarafu.network (just like mint)

**Comment by WillRuddick** [comment]
Edit button with Mint + Community Fund and Other stuff that can change.
