### ISSUE TITLE
Dashboard for network, voucher and User stats

### ISSUE THREAD

**Issue by williamluke4** [grassrootseconomics/sarafu.network#8]
Overall Sarafu.network: (Stats+Graphs)

- [ ] - total accounts, 
- [ ] - daily active users, 
- [ ] - transactions, 
- [ ] - Total number of Vouchers
- [ ] - overlapping line chart for each voucher and the total # transactions)
- [ ] - Possible snapshot of the graph (viz graph)

For individual Vouchers (voucher page):
slider for date range (start and end date)
- [ ] total supply
- [ ] total accounts, 
- [ ] active users
- [ ] transactions
- [ ] Total number of Vouchers
- [ ] Voucher info (editable by admin as well as the user/owner if signed in)

For Users (accounts):
- [ ] - Total number of Vouchers 
- [ ] - Balance for each Voucher
- [ ] - All Transactions
- [ ] - User info ..... (editable by admin as well as the user if signed in)

**Comment by WillRuddick** [comment]
only missing for user. could be on profile ...
